export const GET_TODOLIST_REQUEST = 'GET_TODOLIST_REQUEST';
export const GET_TODOLIST_SUCCESS = 'GET_TODOLIST_SUCCESS';
export const GET_TODOLIST_FAIL = 'GET_TODOLIST_FAIL';

export const GET_TODOLIST_COMPLETED_REQUEST = 'GET_TODOLIST_COMPLETED_REQUEST';
export const GET_TODOLIST_COMPLETED_SUCCESS = 'GET_TODOLIST_COMPLETED_SUCCESS';
export const GET_TODOLIST_COMPLETED_FAIL = 'GET_TODOLIST_COMPLETED_FAIL';

export const PATCH_STATUS_TODOLIST_REQUEST = 'PATCH_STATUS_TODOLIST_REQUEST';
export const PATCH_STATUS_TODOLIST_SUCCESS = 'PATCH_STATUS_TODOLIST_SUCCESS';
export const PATCH_STATUS_TODOLIST_FAIL = 'PATCH_STATUS_TODOLIST_FAIL';

export const GET_TODOLIST_BY_ID_REQUEST = 'GET_TODOLIST_BY_ID_REQUEST';
export const GET_TODOLIST_BY_ID_SUCCESS = 'GET_TODOLIST_BY_ID_SUCCESS';
export const GET_TODOLIST_BY_ID_FAIL = 'GET_TODOLIST_BY_ID_FAIL';

export const PATCH_TODOLIST_REQUEST = 'PATCH_TODOLIST_REQUEST';
export const PATCH_TODOLIST_SUCCESS = 'PATCH_TODOLIST_SUCCESS';
export const PATCH_TODOLIST_FAIL = 'PATCH_TODOLIST_FAIL';

export const DELETE_TODOLIST_REQUEST = 'DELETE_TODOLIST_REQUEST';
export const DELETE_TODOLIST_SUCCESS = 'DELETE_TODOLIST_SUCCESS';
export const DELETE_TODOLIST_FAIL = 'DELETE_TODOLIST_FAIL';

export const POST_TODOLIST_REQUEST = 'PUSH_TODOLIST_REQUEST';
export const POST_TODOLIST_SUCCESS = 'PUSH_TODOLIST_SUCCESS';
export const POST_TODOLIST_FAIL = 'PUSH_TODOLIST_FAIL';